name: min node version
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # Cypress Docker image with minimum Node version
    # we promise to support in this repo
    container: cypress/base:8.16.0
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          spec: 'cypress/integration/07-ci/*'
